/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.chriswk.busdrivers

import java.io.File
import java.nio.charset.Charset

fun main(args: Array<String>) {
    val routes = readRoutes(args[0])
    val day = Day(routes = routes)
    val stop = day.findStop()
    if (stop.isAllGossipKnown()) {
        println("All gossip shared after ${stop.currentMinute} stops")
    } else {
        println("Was never able to share all gossip")
    }
}

fun readRoutes(file: String): List<List<Int>> {
    val f = File(file)
    return f.readLines(Charset.forName("UTF-8"))
        .asSequence()
        .map { line ->
            line.split(" ")
                .map { station -> station.toInt() }
        }.toList()
}